---
- hosts: spacewalk-client
  sudo: yes
  environment:
    no_proxy: "localhost, 127.0.0.1, spacewalk-server"
  roles:
    - role: iptables
      firewall_allowed_tcp_ports:
      - 22
      - 5222
    - role: spacewalk-client
