---
- name: Install Spacewalk repository
  yum:
    name: "{{ spacewalk_server_repo }}"
    state: present

- name: Install all packages for spacewalk proxy
  yum:
    name: ["spacewalk-proxy-selinux", "spacewalk-proxy-installer"]
    state: present

- name: create ssl-build directory
  file:
    path: /root/ssl-build
    state: directory

- name: Copy answers file for spacewalk proxy setup
  template: src=answers.j2 dest=/var/tmp/answers owner=root group=root mode=0600

- name: configure proxy
  command: configure-proxy.sh --answer-file=/var/tmp/answers
    creates=/var/satellite
