- name: Install unattended-upgrades
  package:
    name: unattended-upgrades
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Configure unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Enable automatic updates
  template:
    src: 10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0755
