---
- name: Add apt base channels
  command: spacecmd --user=admin --password={{spacewalk_admin_password}} -- softwarechannel_create -n {{item.name}} -l {{item.label}} -a {{item.arch}} -c sha512
  ignore_errors: true
  with_items: "{{spacewalk_apt_repo_info}}"

- name: Add apt child channels
  command: spacecmd --user=admin --password={{spacewalk_admin_password}} -- softwarechannel_create -n {{item.name}} -p {{item.parent}} -l {{item.label}} -a {{item.arch}} -c sha512
  ignore_errors: true
  with_items: "{{spacewalk_child_apt_repo_info}}"

- name: Add apt repositories
  command: spacecmd --user=admin --password={{spacewalk_admin_password}} -- repo_create -n {{item.name}} -u {{item.repo_url}} -t deb
  ignore_errors: true
  with_items: "{{ spacewalk_apt_repo_info | union(spacewalk_child_apt_repo_info) }}"

- name: Add apt activation keys
  command: spacecmd --user=admin --password={{spacewalk_admin_password}} -- activationkey_create -n {{item.label}} -b {{item.label}} -d {{item.name}}
  ignore_errors: true
  with_items: "{{spacewalk_apt_repo_info}}"

- name: Add activation keys for apt child channels
  command: spacecmd --user=admin --password={{spacewalk_admin_password}} -- activationkey_create -n {{item.label}} -b {{item.parent}} -d {{item.name}}
  ignore_errors: true
  with_items: "{{spacewalk_child_apt_repo_info}}"

- name: Associate apt repos to channels
  command: spacecmd --user=admin --password={{spacewalk_admin_password}} -- softwarechannel_addrepo {{item.label}} {{item.repo}}
  with_items: "{{ spacewalk_apt_repo_info | union(spacewalk_child_apt_repo_info) }}"
  
- name: Associate apt child channels with activationkeys
  command: spacecmd --user=admin --password={{spacewalk_admin_password}} -- activationkey_addchildchannels {{item.activationkey}}  {{item.label}}
  ignore_errors: true
  with_items: "{{spacewalk_child_apt_repo_info}}"
