---
- name: Install dependencies
  yum:
    name: ["spacecmd", "jq", "trickle"]

- name: Copy sql file to fix bug 1661347
  template:
    src: apt_bugfix.sql.j2
    dest: /var/tmp/apt_bugfix.sql
    owner: root
    group: root
    mode: 0600

- name: Copy admin account creation script
  template:
    src: account.sh.j2
    dest: /root/account.sh
    owner: root
    group: root
    mode: 0755

- name: copy upstart script
  template:
    src: pgpass.j2
    dest: /root/.pgpass
    owner: root
    group: root
    mode: 0600

- name: Apply bugfix for 1661347
  shell: "/usr/bin/psql -d {{ spacewalk_db_name }} -U {{ spacewalk_db_user }} < /var/tmp/apt_bugfix.sql"

- name: create admin account
  command: sh /root/account.sh

- name: Install trusted SSL certs
  get_url:
    url: http://localhost/pub/RHN-ORG-TRUSTED-SSL-CERT
    dest: /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT

- name: cleanup sql file for bug 1661347
  file:
    path: /var/tmp/apt_bugfix.sql
    state: absent

- name: cleanup admin account script
  file:
    path: /root/account.sh
    state: absent
