---
spacewalk_admin_email: root@localhost
spacewalk_hostname: spacewalk-server
spacewalk_ip: 10.102.1.101
gpg_pubkeyfileexport: spacewalk.asc

spacewalk_client_repo: "https://copr-be.cloud.fedoraproject.org/results/@spacewalkproject/spacewalk-2.9/epel-{{ansible_distribution_major_version}}-x86_64/00912457-spacewalk-repo/spacewalk-client-repo-2.9-4.el{{ansible_distribution_major_version}}.noarch.rpm"

spacewalk_rhn_org_trusted_ssl_cert_rpm_package: rhn-org-trusted-ssl-cert-1.0-2.noarch.rpm

# Path to the environment file
environment_file: /etc/environment
# The environment file owner
environment_file_owner: root
# The environment file group
environment_file_group: root
